// Code generated by Slice Machine. DO NOT EDIT.

import CardList from './CardList';
import Hero from './Hero';
import Ideas from './Ideas';
import LogoList from './LogoList';
import Metrics from './Metrics';

export {
	CardList,
	Hero,
	Ideas,
	LogoList,
	Metrics,
};

export const components = {
	card_list: CardList,
	hero: Hero,
	ideas: Ideas,
	logo_list: LogoList,
	metrics: Metrics,
};
